# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_entre.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1087, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fond = QtWidgets.QLabel(self.centralwidget)
        self.fond.setGeometry(QtCore.QRect(0, 0, 1071, 721))
        self.fond.setText("")
        self.fond.setPixmap(QtGui.QPixmap("animation/map.jpg"))
        self.fond.setScaledContents(True)
        self.fond.setObjectName("fond")
        self.gros_sacha = QtWidgets.QLabel(self.centralwidget)
        self.gros_sacha.setGeometry(QtCore.QRect(230, 420, 131, 171))
        self.gros_sacha.setText("")
        self.gros_sacha.setPixmap(QtGui.QPixmap("animation/sacha.png"))
        self.gros_sacha.setScaledContents(True)
        self.gros_sacha.setObjectName("gros_sacha")
        self.inventory = QtWidgets.QPushButton(self.centralwidget)
        self.inventory.setGeometry(QtCore.QRect(10, 40, 93, 28))
        self.inventory.setObjectName("inventory")
        self.coeur3 = QtWidgets.QLabel(self.centralwidget)
        self.coeur3.setGeometry(QtCore.QRect(980, 10, 61, 61))
        self.coeur3.setText("")
        self.coeur3.setPixmap(QtGui.QPixmap("animation/coeur.png"))
        self.coeur3.setScaledContents(True)
        self.coeur3.setObjectName("coeur3")
        self.coeur2 = QtWidgets.QLabel(self.centralwidget)
        self.coeur2.setGeometry(QtCore.QRect(920, 10, 61, 61))
        self.coeur2.setText("")
        self.coeur2.setPixmap(QtGui.QPixmap("animation/coeur.png"))
        self.coeur2.setScaledContents(True)
        self.coeur2.setObjectName("coeur2")
        self.coeur1 = QtWidgets.QLabel(self.centralwidget)
        self.coeur1.setGeometry(QtCore.QRect(860, 10, 61, 61))
        self.coeur1.setText("")
        self.coeur1.setPixmap(QtGui.QPixmap("animation/coeur.png"))
        self.coeur1.setScaledContents(True)
        self.coeur1.setObjectName("coeur1")
        self.joueur = QtWidgets.QLineEdit(self.centralwidget)
        self.joueur.setGeometry(QtCore.QRect(10, 10, 113, 22))
        self.joueur.setObjectName("joueur")
        self.pokemon_sauvage = QtWidgets.QLabel(self.centralwidget)
        self.pokemon_sauvage.setGeometry(QtCore.QRect(60, 360, 111, 81))
        self.pokemon_sauvage.setText("")
        self.pokemon_sauvage.setPixmap(QtGui.QPixmap("animation/pikachu.png"))
        self.pokemon_sauvage.setScaledContents(True)
        self.pokemon_sauvage.setObjectName("pokemon_sauvage")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 90, 571, 211))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("animation/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.play = QtWidgets.QPushButton(self.centralwidget)
        self.play.setGeometry(QtCore.QRect(390, 380, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.play.setFont(font)
        self.play.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.play.setAutoFillBackground(True)
        self.play.setObjectName("play")
        self.inventory2 = QtWidgets.QPushButton(self.centralwidget)
        self.inventory2.setGeometry(QtCore.QRect(560, 380, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        self.inventory2.setFont(font)
        self.inventory2.setAutoFillBackground(True)
        self.inventory2.setObjectName("inventory2")
        self.sacha = QtWidgets.QLabel(self.centralwidget)
        self.sacha.setGeometry(QtCore.QRect(390, 580, 19, 25))
        self.sacha.setText("")
        self.sacha.setPixmap(QtGui.QPixmap("animation/down0.png"))
        self.sacha.setScaledContents(True)
        self.sacha.setObjectName("sacha")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1087, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



 

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inventory.setText(_translate("MainWindow", "Inventory"))
        self.joueur.setText(_translate("MainWindow", "Nom Joueur"))
        self.play.setText(_translate("MainWindow", "Play"))
        self.inventory2.setText(_translate("MainWindow", "Inventory"))
        
        
        
        
        
