# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map_poke.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication
from PyQt5.Qt import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        """
        interface graphique

        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 741)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1071, 721))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("animation/map.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 510, 51, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("animation/sacha.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 40, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(980, 10, 61, 61))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("animation/coeur.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(920, 10, 61, 61))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("animation/coeur.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(860, 10, 61, 61))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("animation/coeur.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.psykokwak = QtWidgets.QLabel(self.centralwidget)
        self.psykokwak.setGeometry(QtCore.QRect(80, 360, 91, 81))
        self.psykokwak.setText("")
        self.psykokwak.setPixmap(QtGui.QPixmap("C:/Users/33695/Downloads/cd97b025c6642a1c5722c40c6e41be3c-removebg-preview.png"))
        self.psykokwak.setScaledContents(True)
        self.psykokwak.setObjectName("psykokwak")
        self.label_p = QtWidgets.QLabel(self.centralwidget)
        self.label_p.setGeometry(QtCore.QRect(210,520, 75, 50))
        self.label_p.setText("")
        self.label_p.setPixmap(QtGui.QPixmap("animation/pikachu.png"))
        self.label_p.setScaledContents(True)
        self.label_p.setObjectName("label_p")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

       
   
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Inventary"))
        self.lineEdit.setText(_translate("MainWindow", "Nom Joueur"))

